const STATE = {
    WAITING_FOR_PLAYERS: 'WAITING_FOR_PLAYERS',
    WAITING_FOR_START: 'WAITING_FOR_START',
    DRAWING: 'DRAWING',
    PLAYING: 'PLAYING',
    COUNTING: 'COUNTING',
    ENDED: 'ENDED',
}
export default STATE